### ISSUE TITLE
Attribute / Keyword Clash

### ISSUE THREAD

**Issue by theashguy** [render-rs/render.rs#13]
Something I noticed last night was that the module doesn't *seem* to handle clashes between attributes (like label's `for` or input's `type` nicely). They throw saying they're looking for braces, though I'm pretty sure the intention is not to wrap the attr itself in brace syntax in these situations (unless it is and I've got it wrong!).

Test cases...

`<input type={"checkbox"} />`
`<label for={"some-input-ref"} />`

**Comment by vpzomtrrfrt** [comment]
Is there any workaround for this?
